"use client";
import React, { useState } from "react";
import {
  Description,
  CalendarToday,
  AutoAwesome,
  ExpandMore,
  ExpandLess,
} from "@mui/icons-material";

interface TranscriptViewProps {
  transcriptId?: string;
  onTranscriptChange?: (transcriptId: string) => void;
}

const TranscriptView = ({
  transcriptId = "transcript1",
  onTranscriptChange,
}: TranscriptViewProps) => {
  const [showSummary, setShowSummary] = useState(false);
  const [isTranscriptSelectorOpen, setIsTranscriptSelectorOpen] =
    useState(false);

  const transcripts = [
    { id: "transcript1", name: "Transcript1" },
    { id: "transcript2", name: "Transcript2" },
    { id: "transcript3", name: "Transcript3" },
    { id: "transcript4", name: "Transcript4" },
    { id: "transcript5", name: "Transcript5" },
    { id: "transcript6", name: "Transcript6" },
  ];

  const handleDownloadSummary = () => {
    const transcript =
      transcriptsData[transcriptId] || transcriptsData.transcript1;
    const content = `${transcript.title}\nDate: ${transcript.date} at ${transcript.time}\nDuration: ${transcript.duration}\n\n=== AI SUMMARY ===\n\n${transcript.summary}\n\n=== FULL TRANSCRIPT ===\n\n${transcript.text}\n\nWord count: ${transcript.wordCount} words\nGenerated by Synthai AI`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${transcript.title.replace(
      /[^a-z0-9]/gi,
      "_"
    )}_summary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Data for different transcripts
  const transcriptsData: Record<
    string,
    {
      title: string;
      date: string;
      time: string;
      duration: string;
      text: string;
      summary: string;
      wordCount: number;
    }
  > = {
    transcript1: {
      title: "Team Meeting - Q4 Planning",
      date: "May 12, 2025",
      time: "2:30 PM",
      duration: "45 minutes",
      text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.

Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.`,
      summary: `This is a comprehensive discussion about Q4 planning for the team. Key points include:

• Setting quarterly objectives and key results (OKRs)
• Resource allocation and budget planning
• Timeline for major initiatives
• Risk assessment and mitigation strategies
• Team capacity and workload distribution

The meeting concluded with clear action items and deadlines for all team members.`,
      wordCount: 245,
    },
    transcript2: {
      title: "Product Research Analysis",
      date: "May 10, 2025",
      time: "10:00 AM",
      duration: "60 minutes",
      text: `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.

Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.

Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
      summary: `Product research findings highlight customer needs and market opportunities:

• Strong demand for automated features
• Users prefer intuitive interfaces
• Mobile-first approach is critical
• Integration with existing tools is essential
• Pricing sensitivity varies by market segment

Recommendations include prioritizing user experience improvements and expanding mobile capabilities.`,
      wordCount: 312,
    },
    transcript3: {
      title: "Customer Interview Insights",
      date: "May 8, 2025",
      time: "3:15 PM",
      duration: "30 minutes",
      text: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.

Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.`,
      summary: `Customer feedback reveals key insights about product usage:

• Primary use case is workflow automation
• Users struggle with initial setup
• Support documentation needs improvement
• Feature requests focus on collaboration tools
• High satisfaction with core functionality

Action items include improving onboarding and expanding help resources.`,
      wordCount: 189,
    },
    transcript4: {
      title: "Market Trends Report",
      date: "May 5, 2025",
      time: "11:30 AM",
      duration: "50 minutes",
      text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.

Omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus.`,
      summary: `Market analysis indicates emerging trends and opportunities:

• AI adoption accelerating across industries
• Remote work driving software demand
• Security and privacy becoming top priorities
• Subscription models preferred over perpetual licenses
• Integration capabilities are differentiators

Strategic recommendations include investing in AI features and strengthening security posture.`,
      wordCount: 428,
    },
    transcript5: {
      title: "Training Session Notes",
      date: "May 3, 2025",
      time: "9:00 AM",
      duration: "90 minutes",
      text: `Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt.

Ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.

Vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.`,
      summary: `Training session covered essential topics and best practices:

• Introduction to platform features
• Step-by-step workflow demonstrations
• Common troubleshooting scenarios
• Advanced tips and shortcuts
• Q&A addressing participant questions

Attendees gained practical skills and confidence in using the platform effectively.`,
      wordCount: 267,
    },
    transcript6: {
      title: "Project Retrospective",
      date: "May 1, 2025",
      time: "4:00 PM",
      duration: "40 minutes",
      text: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.

Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.

Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`,
      summary: `Project retrospective identified successes and areas for improvement:

• Successfully delivered all major features on time
• Strong collaboration between teams
• Communication gaps caused minor delays
• Technical debt needs addressing
• Documentation requires updates

Next steps include implementing lessons learned and planning process improvements.`,
      wordCount: 298,
    },
  };

  const currentTranscript =
    transcriptsData[transcriptId] || transcriptsData.transcript1;

  return (
    <div className="w-full flex flex-col items-center py-12 px-4 pb-20 md:pb-12">
      <div className="w-full max-w-[370px] md:max-w-none">
        {/* Mobile Transcript Selector - visible only on mobile */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-4 mb-6 md:hidden">
          <button
            onClick={() =>
              setIsTranscriptSelectorOpen(!isTranscriptSelectorOpen)
            }
            className="w-full flex items-center justify-between text-left py-2 px-3 text-primary hover:bg-primary/5 rounded-lg transition-colors"
          >
            <div className="flex items-center gap-2">
              <Description className="text-lg" />
              <span className="font-semibold">
                {transcripts.find((t) => t.id === transcriptId)?.name ||
                  "Select Transcript"}
              </span>
            </div>
            {isTranscriptSelectorOpen ? (
              <ExpandLess className="text-lg" />
            ) : (
              <ExpandMore className="text-lg" />
            )}
          </button>

          {isTranscriptSelectorOpen && (
            <div className="mt-2 border-t border-outline pt-2">
              {transcripts.map((transcript) => (
                <button
                  key={transcript.id}
                  onClick={() => {
                    if (onTranscriptChange) {
                      onTranscriptChange(transcript.id);
                    }
                    setIsTranscriptSelectorOpen(false);
                  }}
                  className={`w-full text-left py-2 px-3 rounded-lg transition-colors flex items-center gap-2 ${
                    transcriptId === transcript.id
                      ? "bg-primary/10 text-primary"
                      : "text-text hover:bg-primary/5"
                  }`}
                >
                  <Description className="text-sm" />
                  {transcript.name}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Header */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-8 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-4">
              <Description className="text-primary text-4xl" />
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-primary">
                  {currentTranscript.title}
                </h1>
                <div className="flex items-center gap-4 mt-2">
                  <div className="flex items-center gap-2 text-muted">
                    <CalendarToday className="text-sm" />
                    <span>
                      {currentTranscript.date} at {currentTranscript.time}
                    </span>
                  </div>
                  <div className="text-muted">
                    <span>Duration: {currentTranscript.duration}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-6 mb-8">
          <div className="flex gap-4 justify-center">
            <button
              onClick={() => setShowSummary(!showSummary)}
              className="flex items-center gap-2 px-6 py-3 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
            >
              <AutoAwesome className="text-lg" />
              {showSummary ? "Hide Summary" : "Generate Summary"}
            </button>
            <button
              onClick={handleDownloadSummary}
              className="px-6 py-3 border border-outline text-text rounded-lg hover:border-primary hover:text-primary transition-colors"
            >
              Download Summary
            </button>
          </div>
        </div>

        {/* Summary Section */}
        {showSummary && (
          <div className="w-full bg-gradient-to-r from-primary/5 to-secondary/5 rounded-2xl shadow-lg p-8 mb-8 border border-primary/20">
            <div className="flex items-center gap-3 mb-4">
              <AutoAwesome className="text-primary text-2xl" />
              <h2 className="text-xl font-semibold text-primary">AI Summary</h2>
            </div>
            <div className="bg-surface rounded-lg p-6">
              <p className="text-text leading-relaxed whitespace-pre-line">
                {currentTranscript.summary}
              </p>
            </div>
          </div>
        )}

        {/* Transcript Content */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-8">
          <h2 className="text-xl font-semibold text-primary mb-6">
            Transcript Content
          </h2>
          <div className="bg-background rounded-lg p-6 border border-outline">
            <p className="text-text leading-relaxed text-justify whitespace-pre-line">
              {currentTranscript.text}
            </p>
          </div>

          {/* Transcript Footer */}
          <div className="mt-6 pt-6 border-t border-outline flex items-center justify-between text-sm text-muted">
            <span>Word count: {currentTranscript.wordCount} words</span>
            <span>Generated by Synthai AI</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TranscriptView;
