"use client";
import React, { useState, useMemo } from "react";
import {
  Description,
  CalendarToday,
  AutoAwesome,
  ExpandMore,
  ExpandLess,
} from "@mui/icons-material";
import { useParams, useRouter } from "next/navigation";
import transcriptsData from "./Transcripts";

function TranscriptView() {
  const [showSummary, setShowSummary] = useState(false);
  const params = useParams();
  const transcriptId = params?.id; 
  const router = useRouter();
  const [isTranscriptSelectorOpen, setIsTranscriptSelectorOpen] =
    useState(false);

  const transcripts = transcriptsData.map((t) => ({ id: t.id, name: t.title }));

  const currentTranscript = useMemo(() => {
    return transcriptsData.find((t) => t.id === Number(transcriptId));
  }, [transcriptId]);
  
  // Early exit if the transcript is not found
  if (!currentTranscript) {
    return (
      <div className="w-full md:w-4/5 pt-4 min-h-screen mx-auto mt-20 md:mt-8 text-center p-4">
        <p className="text-xl font-semibold text-text">
          Transcript with ID {transcriptId} not found.
        </p>
        <button
              onClick={() => router.push('/')} // Or some appropriate route
              className="mt-4 px-6 py-3 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
            >
              Go to Home
            </button>
      </div>
    );
  }

  const handleDownloadSummary = () => {
    // currentTranscript is guaranteed to exist here due to the early exit
    const transcript = currentTranscript; 
    
    const content = `${transcript.title}\nDate: ${transcript.date} at ${transcript.time}\nDuration: ${transcript.duration}\n\n=== AI SUMMARY ===\n\n${transcript.summary}\n\n=== FULL TRANSCRIPT ===\n\n${transcript.text}\n\nWord count: ${transcript.wordCount} words\nGenerated by Synthai AI`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${transcript.title.replace(
      /[^a-z0-9]/gi,
      "_"
    )}_summary.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className=" w-full md:w-4/5 mx-auto flex flex-col items-center pt-6 px-4 mt-20 md:mt-8 ">
      <div className="w-full max-w-[370px] md:max-w-none">
        {/* Mobile Transcript Selector - visible only on mobile */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-4 mb-6 md:hidden">
          <button
            onClick={() =>
              setIsTranscriptSelectorOpen(!isTranscriptSelectorOpen)
            }
            className="w-full flex items-center justify-between text-left py-2 px-3 text-primary hover:bg-primary/5 rounded-lg transition-colors"
          >
            <div className="flex items-center gap-2">
              <Description className="text-lg" />
              <span className="font-semibold">
                {currentTranscript.title || "Select Transcript"}
              </span>
            </div>
            {isTranscriptSelectorOpen ? (
              <ExpandLess className="text-lg" />
            ) : (
              <ExpandMore className="text-lg" />
            )}
          </button>

          {isTranscriptSelectorOpen && (
            <div className="mt-2 border-t border-outline pt-2">
              {transcripts.map((transcript) => (
                <button
                  key={transcript.id}
                  onClick={() => {
                    router.push(`/transcripts/${transcript.id}`);
                    setIsTranscriptSelectorOpen(false); // Close selector after clicking
                  }}
                  className={`w-full text-left py-2 px-3 rounded-lg transition-colors flex items-center gap-2 ${
                    Number(transcriptId) === transcript.id // Use Number(transcriptId) for correct comparison
                      ? "bg-primary/10 text-primary"
                      : "text-text hover:bg-primary/5"
                  }`}
                >
                  <Description className="text-sm" />
                  {transcript.name}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Header */}
        <div className="w-full bg-surface rounded-2xl shadow-lg p-8 mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-4">
              <Description className="text-primary text-4xl" />
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-primary">
                  {currentTranscript.title}
                </h1>
                <div className="flex items-center gap-4 mt-2">
                  <div className="flex items-center gap-2 text-muted">
                    <CalendarToday className="text-sm" />
                    <span>
                      {currentTranscript.date} at {currentTranscript.time}
                    </span>
                  </div>
                  <div className="text-muted">
                    <span>Duration: {currentTranscript.duration}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="w-full mb-8 bg-surface rounded-2xl shadow-lg p-6 ">
          <div className="flex gap-4 justify-center">
            <button
              onClick={() => setShowSummary(!showSummary)}
              className="flex items-center gap-2 px-6 py-3 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
            >
              <AutoAwesome className="text-lg" />
              {showSummary ? "Hide Summary" : "Generate Summary"}
            </button>
            <button
              onClick={handleDownloadSummary}
              className="px-6 py-3 border border-outline text-text rounded-lg hover:border-primary hover:text-primary transition-colors"
            >
              Download Summary
            </button>
          </div>
        </div>

        {/* Summary Section */}
        {showSummary && (
          <div className="w-full bg-gradient-to-r from-primary/5 to-secondary/5 rounded-2xl shadow-lg p-8 mb-8 border border-outline">
            <div className="flex items-center gap-3 mb-4">
              <AutoAwesome className="text-primary text-2xl" />
              <h2 className="text-xl font-semibold text-primary">AI Summary</h2>
            </div>
            <div className="bg-surface rounded-lg p-6">
              <p className="text-text leading-relaxed whitespace-pre-line">
                {currentTranscript.summary}
              </p>
            </div>
          </div>
        )}

        {/* Transcript Content */}
        <div className="w-full bg-surface rounded-2xl shadow-lg mb-8 p-8">
          <h2 className="text-xl font-semibold text-primary mb-6">
            Transcript Content
          </h2>
          <div className="bg-background rounded-lg p-6 border border-outline">
            <p className="text-text leading-relaxed text-justify whitespace-pre-line">
              {currentTranscript.text}
            </p>
          </div>

          {/* Transcript Footer */}
          <div className="mt-6 pt-6 border-t border-outline flex items-center justify-between text-sm text-muted">
            <span>Word count: {currentTranscript.wordCount} words</span>
            <span>Generated by Synthai AI</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TranscriptView;